version: "3.7"
services:
  # PostgreSQL container setup
  postgres:
    image: postgres:10.0-alpine
    container_name: pgs_db
    environment:
      - POSTGRES_USER=abfg_user
      - POSTGRES_PASSWORD=some_pwd
      - POSTGRES_DB=abfg_db
    ports:
      - "54321:5432"
    networks:
      db-net:
        aliases:
          - postgres

  # ABF-Guard service
  abf-guard:
    container_name: abfg
    build:
      context: ../.
      dockerfile: ./deployments/abfg-service/Dockerfile
    volumes:
      - ../configs:/opt/abf-guard/configs
    depends_on:
      - postgres
    ports:
      - "6666:6666"
    networks:
      db-net:
        aliases:
          - abf-guard
    restart: on-failure

  # Integration tests
  integration_tests:
    build:
      context: ../.
      dockerfile: ./deployments/abfg-integration-test/Dockerfile
    depends_on:
      - postgres
      - abf-guard
    restart: on-failure
    networks:
      - db-net

# Network definitions
networks:
  db-net:
    driver: bridge
