version: "3.7"
services:
  # PostgreSQL container setup
  postgres:
    image: postgres:10.0-alpine
    container_name: pgs_db
    environment:
      - POSTGRES_USER=abfg_user
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_DB=abfg_db
    volumes:
      - ../db/001.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54321:5432"
    networks:
      db-net:
        aliases:
          - postgres

  # ABF-Guard service
  abf-guard:
    container_name: abfg
    build:
      context: ../.
      dockerfile: abfg-service/abfg-service.Dockerfile
    volumes:
      - ../configs:/opt/abf-guard/configs
    depends_on:
      - postgres
    ports:
      - "7070:6666"
    networks:
      db-net:
        aliases:
          - abf-guard
    restart: on-failure

# Network definitions
networks:
  db-net:
    driver: bridge
