// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/abf-guard.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AuthorisationRequest is a message that is being send while trying to log in to a resource
type AuthorisationRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorisationRequest) Reset()         { *m = AuthorisationRequest{} }
func (m *AuthorisationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorisationRequest) ProtoMessage()    {}
func (*AuthorisationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d920cdee07ab3e, []int{0}
}

func (m *AuthorisationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorisationRequest.Unmarshal(m, b)
}
func (m *AuthorisationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorisationRequest.Marshal(b, m, deterministic)
}
func (m *AuthorisationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorisationRequest.Merge(m, src)
}
func (m *AuthorisationRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorisationRequest.Size(m)
}
func (m *AuthorisationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorisationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorisationRequest proto.InternalMessageInfo

func (m *AuthorisationRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthorisationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthorisationRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

// Response is a return message that is used by all rpc methods; returns either a boolean response or an error
type Response struct {
	// Types that are valid to be assigned to Result:
	//	*Response_Ok
	//	*Response_Error
	Result               isResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d920cdee07ab3e, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_Result interface {
	isResponse_Result()
}

type Response_Ok struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3,oneof"`
}

type Response_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*Response_Ok) isResponse_Result() {}

func (*Response_Error) isResponse_Result() {}

func (m *Response) GetResult() isResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Response) GetOk() bool {
	if x, ok := m.GetResult().(*Response_Ok); ok {
		return x.Ok
	}
	return false
}

func (m *Response) GetError() string {
	if x, ok := m.GetResult().(*Response_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Ok)(nil),
		(*Response_Error)(nil),
	}
}

// FlushBucketRequest is a message that contains information on a bucket that needs to be flushed
type FlushBucketRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlushBucketRequest) Reset()         { *m = FlushBucketRequest{} }
func (m *FlushBucketRequest) String() string { return proto.CompactTextString(m) }
func (*FlushBucketRequest) ProtoMessage()    {}
func (*FlushBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d920cdee07ab3e, []int{2}
}

func (m *FlushBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlushBucketRequest.Unmarshal(m, b)
}
func (m *FlushBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlushBucketRequest.Marshal(b, m, deterministic)
}
func (m *FlushBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlushBucketRequest.Merge(m, src)
}
func (m *FlushBucketRequest) XXX_Size() int {
	return xxx_messageInfo_FlushBucketRequest.Size(m)
}
func (m *FlushBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FlushBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FlushBucketRequest proto.InternalMessageInfo

func (m *FlushBucketRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *FlushBucketRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

// FlushBucketRequest is a message that contains information on a bucket that needs to be flushed
type PurgeBucketRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurgeBucketRequest) Reset()         { *m = PurgeBucketRequest{} }
func (m *PurgeBucketRequest) String() string { return proto.CompactTextString(m) }
func (*PurgeBucketRequest) ProtoMessage()    {}
func (*PurgeBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d920cdee07ab3e, []int{3}
}

func (m *PurgeBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeBucketRequest.Unmarshal(m, b)
}
func (m *PurgeBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeBucketRequest.Marshal(b, m, deterministic)
}
func (m *PurgeBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeBucketRequest.Merge(m, src)
}
func (m *PurgeBucketRequest) XXX_Size() int {
	return xxx_messageInfo_PurgeBucketRequest.Size(m)
}
func (m *PurgeBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeBucketRequest proto.InternalMessageInfo

func (m *PurgeBucketRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// SubnetRequest is a message that is used to request black and white lists actions
type SubnetRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	List                 bool     `protobuf:"varint,2,opt,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubnetRequest) Reset()         { *m = SubnetRequest{} }
func (m *SubnetRequest) String() string { return proto.CompactTextString(m) }
func (*SubnetRequest) ProtoMessage()    {}
func (*SubnetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d920cdee07ab3e, []int{4}
}

func (m *SubnetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubnetRequest.Unmarshal(m, b)
}
func (m *SubnetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubnetRequest.Marshal(b, m, deterministic)
}
func (m *SubnetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetRequest.Merge(m, src)
}
func (m *SubnetRequest) XXX_Size() int {
	return xxx_messageInfo_SubnetRequest.Size(m)
}
func (m *SubnetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetRequest proto.InternalMessageInfo

func (m *SubnetRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *SubnetRequest) GetList() bool {
	if m != nil {
		return m.List
	}
	return false
}

// SubnetRequest is a message that is used to request black and white lists actions
type ListRequest struct {
	ListType             bool     `protobuf:"varint,1,opt,name=listType,proto3" json:"listType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d920cdee07ab3e, []int{5}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetListType() bool {
	if m != nil {
		return m.ListType
	}
	return false
}

// IpList is a message that holds all the IP addresses stored either in the whitelist or the blacklist
type IPList struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPList) Reset()         { *m = IPList{} }
func (m *IPList) String() string { return proto.CompactTextString(m) }
func (*IPList) ProtoMessage()    {}
func (*IPList) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d920cdee07ab3e, []int{6}
}

func (m *IPList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPList.Unmarshal(m, b)
}
func (m *IPList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPList.Marshal(b, m, deterministic)
}
func (m *IPList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPList.Merge(m, src)
}
func (m *IPList) XXX_Size() int {
	return xxx_messageInfo_IPList.Size(m)
}
func (m *IPList) XXX_DiscardUnknown() {
	xxx_messageInfo_IPList.DiscardUnknown(m)
}

var xxx_messageInfo_IPList proto.InternalMessageInfo

func (m *IPList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

// SubnetRequest is a message that is used to request black and white lists actions
type ListResponse struct {
	// Types that are valid to be assigned to Result:
	//	*ListResponse_Ips
	//	*ListResponse_Error
	Result               isListResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d920cdee07ab3e, []int{7}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

type isListResponse_Result interface {
	isListResponse_Result()
}

type ListResponse_Ips struct {
	Ips *IPList `protobuf:"bytes,1,opt,name=ips,proto3,oneof"`
}

type ListResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListResponse_Ips) isListResponse_Result() {}

func (*ListResponse_Error) isListResponse_Result() {}

func (m *ListResponse) GetResult() isListResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ListResponse) GetIps() *IPList {
	if x, ok := m.GetResult().(*ListResponse_Ips); ok {
		return x.Ips
	}
	return nil
}

func (m *ListResponse) GetError() string {
	if x, ok := m.GetResult().(*ListResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListResponse_Ips)(nil),
		(*ListResponse_Error)(nil),
	}
}

func init() {
	proto.RegisterType((*AuthorisationRequest)(nil), "AuthorisationRequest")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*FlushBucketRequest)(nil), "FlushBucketRequest")
	proto.RegisterType((*PurgeBucketRequest)(nil), "PurgeBucketRequest")
	proto.RegisterType((*SubnetRequest)(nil), "SubnetRequest")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*IPList)(nil), "IPList")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
}

func init() { proto.RegisterFile("api/abf-guard.proto", fileDescriptor_79d920cdee07ab3e) }

var fileDescriptor_79d920cdee07ab3e = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0xd3, 0x94, 0x15, 0xf7, 0xb6, 0x9d, 0x26, 0x77, 0x43, 0x55, 0xe1, 0x61, 0xf2, 0xd3,
	0x40, 0xc2, 0x43, 0x2b, 0x4f, 0x3c, 0x20, 0xb5, 0x42, 0x5d, 0x2b, 0x81, 0x14, 0x99, 0x49, 0xf0,
	0x9a, 0x2e, 0xa6, 0xb5, 0x92, 0xc5, 0xc6, 0x7f, 0x84, 0xf8, 0x2e, 0x7c, 0x58, 0x14, 0xbb, 0xcb,
	0x12, 0x86, 0x60, 0x7b, 0xf3, 0xbd, 0xf1, 0xf9, 0x9d, 0xe8, 0x9c, 0x04, 0xc6, 0xa9, 0x12, 0xe7,
	0xe9, 0xe6, 0xdb, 0xeb, 0xad, 0x4b, 0x75, 0x46, 0x95, 0x96, 0x56, 0x92, 0xaf, 0x70, 0x3c, 0x77,
	0x76, 0x27, 0xb5, 0x30, 0xa9, 0x15, 0xb2, 0x64, 0xfc, 0xbb, 0xe3, 0xc6, 0xe2, 0x63, 0x38, 0x28,
	0xe4, 0x56, 0x94, 0x93, 0xce, 0x69, 0xe7, 0xac, 0xcf, 0xc2, 0x80, 0xa7, 0x80, 0x54, 0x6a, 0xcc,
	0x0f, 0xa9, 0xb3, 0x49, 0xec, 0x1f, 0xd4, 0x33, 0x3e, 0x84, 0x58, 0xa8, 0x49, 0xd7, 0x6f, 0x63,
	0xa1, 0xc8, 0x7b, 0x40, 0x8c, 0x1b, 0x25, 0x4b, 0xc3, 0xf1, 0x11, 0xc4, 0x32, 0xf7, 0x28, 0xb4,
	0x8a, 0x58, 0x2c, 0x73, 0xfc, 0x0c, 0x0e, 0xb8, 0xd6, 0x52, 0x07, 0xcc, 0x2a, 0x62, 0x61, 0x5c,
	0x20, 0xe8, 0x69, 0x6e, 0x5c, 0x61, 0xc9, 0x3b, 0xc0, 0xcb, 0xc2, 0x99, 0xdd, 0xc2, 0x5d, 0xe7,
	0xdc, 0xfe, 0xfb, 0xbd, 0x82, 0x77, 0x5c, 0x7b, 0x9f, 0x01, 0x4e, 0x9c, 0xde, 0xf2, 0xb6, 0x16,
	0xc3, 0x93, 0x32, 0xbd, 0xe1, 0x7b, 0xa9, 0x3f, 0x93, 0x19, 0x8c, 0x3e, 0xbb, 0x4d, 0x79, 0x77,
	0x29, 0xa0, 0x3a, 0xb7, 0xa8, 0x4a, 0x54, 0x08, 0x63, 0x3d, 0x1c, 0x31, 0x7f, 0x26, 0x2f, 0x61,
	0xf0, 0x51, 0x98, 0x5a, 0x32, 0x05, 0x54, 0xad, 0xaf, 0x7e, 0xaa, 0xc0, 0x46, 0xac, 0x9e, 0xc9,
	0x0b, 0xe8, 0xad, 0x93, 0xea, 0x72, 0x0d, 0xea, 0x9c, 0x76, 0x2b, 0x77, 0x0f, 0xfa, 0x04, 0xc3,
	0x00, 0xda, 0xe7, 0xf4, 0x1c, 0xba, 0x42, 0x19, 0x0f, 0x19, 0x5c, 0x3c, 0xa5, 0x41, 0xb9, 0x8a,
	0x58, 0xb5, 0xfd, 0x7f, 0x64, 0x17, 0xbf, 0xba, 0x80, 0xe6, 0x8b, 0xe5, 0x65, 0xd5, 0x2f, 0x9e,
	0xc1, 0xa8, 0xd5, 0x2c, 0x3e, 0xa1, 0x7f, 0x6b, 0x7a, 0xda, 0xa7, 0xb7, 0xf6, 0x24, 0xc2, 0x6f,
	0x60, 0xd8, 0x08, 0xdd, 0xe0, 0x31, 0xbd, 0xdf, 0x41, 0x5b, 0x71, 0x0e, 0x83, 0x46, 0xd4, 0x78,
	0x4c, 0xef, 0x07, 0xff, 0xa7, 0xe0, 0x68, 0x9e, 0x65, 0xeb, 0xe4, 0x4a, 0x7e, 0xd9, 0x09, 0xcb,
	0xab, 0x1c, 0xf0, 0x21, 0x6d, 0x95, 0xd0, 0x16, 0xbc, 0x85, 0x93, 0x0f, 0xbc, 0xe0, 0x96, 0xaf,
	0x93, 0xa5, 0x96, 0x37, 0x0f, 0x54, 0xdd, 0xd9, 0x2c, 0x8a, 0xf4, 0x3a, 0x7f, 0xb4, 0xcd, 0x03,
	0x55, 0xaf, 0xa0, 0x7f, 0xc9, 0xed, 0xbe, 0xe2, 0x21, 0x6d, 0x7c, 0x16, 0xd3, 0x11, 0x6d, 0x76,
	0x4b, 0xa2, 0x4d, 0xcf, 0xff, 0x72, 0xb3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0xe6, 0x6c,
	0x3a, 0x89, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ABFGuardClient is the client API for ABFGuard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ABFGuardClient interface {
	// Authorisation sends the authorisation request
	Authorisation(ctx context.Context, in *AuthorisationRequest, opts ...grpc.CallOption) (*Response, error)
	// FlashBuckets sends a request to flush the buckets for the specified login and ip
	FlushBuckets(ctx context.Context, in *FlushBucketRequest, opts ...grpc.CallOption) (*Response, error)
	// PurgeBucket sends a request to purge the specified bucket
	PurgeBucket(ctx context.Context, in *PurgeBucketRequest, opts ...grpc.CallOption) (*Response, error)
	// AddIpToWhitelist sends a request to add the specified subnet to the whitelist
	AddIPToWhitelist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*Response, error)
	// DeleteIpFromWhitelist sends a request to remove the specified subnet from the whitelist
	DeleteIPFromWhitelist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*Response, error)
	// AddIpToBlacklist sends a request to add the specified subnet to the blacklist
	AddIPToBlacklist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*Response, error)
	// DeleteIpFromBlacklist sends a request to remove the specified subnet from the blacklist
	DeleteIPFromBlacklist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*Response, error)
	// GetWhiteList send sa request to retrieve an ip list from a specified list
	GetIPList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type aBFGuardClient struct {
	cc *grpc.ClientConn
}

func NewABFGuardClient(cc *grpc.ClientConn) ABFGuardClient {
	return &aBFGuardClient{cc}
}

func (c *aBFGuardClient) Authorisation(ctx context.Context, in *AuthorisationRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ABFGuard/Authorisation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBFGuardClient) FlushBuckets(ctx context.Context, in *FlushBucketRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ABFGuard/FlushBuckets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBFGuardClient) PurgeBucket(ctx context.Context, in *PurgeBucketRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ABFGuard/PurgeBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBFGuardClient) AddIPToWhitelist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ABFGuard/AddIPToWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBFGuardClient) DeleteIPFromWhitelist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ABFGuard/DeleteIPFromWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBFGuardClient) AddIPToBlacklist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ABFGuard/AddIPToBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBFGuardClient) DeleteIPFromBlacklist(ctx context.Context, in *SubnetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ABFGuard/DeleteIPFromBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBFGuardClient) GetIPList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/ABFGuard/GetIPList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ABFGuardServer is the server API for ABFGuard service.
type ABFGuardServer interface {
	// Authorisation sends the authorisation request
	Authorisation(context.Context, *AuthorisationRequest) (*Response, error)
	// FlashBuckets sends a request to flush the buckets for the specified login and ip
	FlushBuckets(context.Context, *FlushBucketRequest) (*Response, error)
	// PurgeBucket sends a request to purge the specified bucket
	PurgeBucket(context.Context, *PurgeBucketRequest) (*Response, error)
	// AddIpToWhitelist sends a request to add the specified subnet to the whitelist
	AddIPToWhitelist(context.Context, *SubnetRequest) (*Response, error)
	// DeleteIpFromWhitelist sends a request to remove the specified subnet from the whitelist
	DeleteIPFromWhitelist(context.Context, *SubnetRequest) (*Response, error)
	// AddIpToBlacklist sends a request to add the specified subnet to the blacklist
	AddIPToBlacklist(context.Context, *SubnetRequest) (*Response, error)
	// DeleteIpFromBlacklist sends a request to remove the specified subnet from the blacklist
	DeleteIPFromBlacklist(context.Context, *SubnetRequest) (*Response, error)
	// GetWhiteList send sa request to retrieve an ip list from a specified list
	GetIPList(context.Context, *ListRequest) (*ListResponse, error)
}

// UnimplementedABFGuardServer can be embedded to have forward compatible implementations.
type UnimplementedABFGuardServer struct {
}

func (*UnimplementedABFGuardServer) Authorisation(ctx context.Context, req *AuthorisationRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorisation not implemented")
}
func (*UnimplementedABFGuardServer) FlushBuckets(ctx context.Context, req *FlushBucketRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlushBuckets not implemented")
}
func (*UnimplementedABFGuardServer) PurgeBucket(ctx context.Context, req *PurgeBucketRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeBucket not implemented")
}
func (*UnimplementedABFGuardServer) AddIPToWhitelist(ctx context.Context, req *SubnetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIPToWhitelist not implemented")
}
func (*UnimplementedABFGuardServer) DeleteIPFromWhitelist(ctx context.Context, req *SubnetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIPFromWhitelist not implemented")
}
func (*UnimplementedABFGuardServer) AddIPToBlacklist(ctx context.Context, req *SubnetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIPToBlacklist not implemented")
}
func (*UnimplementedABFGuardServer) DeleteIPFromBlacklist(ctx context.Context, req *SubnetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIPFromBlacklist not implemented")
}
func (*UnimplementedABFGuardServer) GetIPList(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIPList not implemented")
}

func RegisterABFGuardServer(s *grpc.Server, srv ABFGuardServer) {
	s.RegisterService(&_ABFGuard_serviceDesc, srv)
}

func _ABFGuard_Authorisation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorisationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABFGuardServer).Authorisation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABFGuard/Authorisation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABFGuardServer).Authorisation(ctx, req.(*AuthorisationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABFGuard_FlushBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABFGuardServer).FlushBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABFGuard/FlushBuckets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABFGuardServer).FlushBuckets(ctx, req.(*FlushBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABFGuard_PurgeBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABFGuardServer).PurgeBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABFGuard/PurgeBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABFGuardServer).PurgeBucket(ctx, req.(*PurgeBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABFGuard_AddIPToWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABFGuardServer).AddIPToWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABFGuard/AddIPToWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABFGuardServer).AddIPToWhitelist(ctx, req.(*SubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABFGuard_DeleteIPFromWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABFGuardServer).DeleteIPFromWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABFGuard/DeleteIPFromWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABFGuardServer).DeleteIPFromWhitelist(ctx, req.(*SubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABFGuard_AddIPToBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABFGuardServer).AddIPToBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABFGuard/AddIPToBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABFGuardServer).AddIPToBlacklist(ctx, req.(*SubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABFGuard_DeleteIPFromBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABFGuardServer).DeleteIPFromBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABFGuard/DeleteIPFromBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABFGuardServer).DeleteIPFromBlacklist(ctx, req.(*SubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABFGuard_GetIPList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABFGuardServer).GetIPList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ABFGuard/GetIPList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABFGuardServer).GetIPList(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ABFGuard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ABFGuard",
	HandlerType: (*ABFGuardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorisation",
			Handler:    _ABFGuard_Authorisation_Handler,
		},
		{
			MethodName: "FlushBuckets",
			Handler:    _ABFGuard_FlushBuckets_Handler,
		},
		{
			MethodName: "PurgeBucket",
			Handler:    _ABFGuard_PurgeBucket_Handler,
		},
		{
			MethodName: "AddIPToWhitelist",
			Handler:    _ABFGuard_AddIPToWhitelist_Handler,
		},
		{
			MethodName: "DeleteIPFromWhitelist",
			Handler:    _ABFGuard_DeleteIPFromWhitelist_Handler,
		},
		{
			MethodName: "AddIPToBlacklist",
			Handler:    _ABFGuard_AddIPToBlacklist_Handler,
		},
		{
			MethodName: "DeleteIPFromBlacklist",
			Handler:    _ABFGuard_DeleteIPFromBlacklist_Handler,
		},
		{
			MethodName: "GetIPList",
			Handler:    _ABFGuard_GetIPList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/abf-guard.proto",
}
